Repository Team-FloWee/kovel-app, pull requests merged in 2024-05, with the labels that each got.

#143 Feat/login process
  lib/config/ui_config.dart
  lib/core/enum/login_platform.dart
  lib/core/router/router.dart
  lib/data/data_source/firebase/user_data_source.dart
  lib/data/data_source/firebase/user_data_source_impl.dart
  lib/data/repository_impl/auth/google_auth.dart
  lib/data/repository_impl/auth/kakao_auth.dart
  lib/data/repository_impl/user_repository_impl.dart
  lib/di/di_setup.dart
  lib/domain/repository/auth/social_auth.dart
  lib/domain/repository/user_repository.dart
  lib/domain/use_case/auth/login_use_case.dart
  lib/domain/use_case/auth/logout_use_case.dart
  lib/presentation/login/google_login.dart
  lib/presentation/login/kakao_login.dart
  lib/presentation/login/login_screen.dart
  lib/presentation/login/login_view_model.dart
  lib/presentation/login/social_login.dart
  lib/presentation/sign_up/sign_up_screen.dart
  lib/presentation/sign_up/sign_up_view_model.dart
Labels: feat

#166 feat: create pagination function
  lib/data/repository_impl/tour_info_repository_impl.dart
  lib/domain/use_case/get_area_data_use_case.dart
  lib/domain/use_case/get_common_data_use_case.dart
  lib/presentation/components/common_app_bar.dart
  lib/presentation/location_list/location_list_screen.dart
  lib/presentation/location_list/location_list_view_model.dart
Labels: feat

#169 Feat/connect gemini
  lib/core/service/ai_provider.dart
  lib/data/data_source/ai_data_source.dart
  lib/data/data_source/ai_data_source_impl.dart
  lib/data/repository_impl/ai_repository_impl.dart
  lib/di/di_setup.dart
  lib/domain/repository/ai_repository.dart
  lib/domain/use_case/ai/get_translated_data_stream_use_case.dart
  lib/presentation/components/translate/context_menu.dart
  lib/presentation/components/translate/translate_bottom_sheet.dart
  lib/presentation/detail/detail_screen.dart
  pubspec.yaml
Labels: feat

#180 Feat/edit bottom navibar
  lib/core/router/router.dart
  lib/presentation/archived/archived_screen.dart
  lib/presentation/components/bottom_navi_bar.dart
  lib/presentation/home/home_screen.dart
  lib/presentation/my_page/my_page_screen.dart
Labels: feat

#181 refactor/refactor-archived
  lib/core/auth/user_provider.dart
  lib/data/data_source/firebase/liked_tour_data_source.dart
  lib/data/data_source/firebase/liked_tour_data_source_impl.dart
  lib/data/repository_impl/firebase/liked_tour_repository_impl.dart
  lib/di/di_setup.dart
  lib/domain/repository/firebase/liked_tour_repository.dart
  lib/domain/use_case/like_tour_use_case.dart
  lib/domain/use_case/unlike_tour_use_case.dart
  lib/presentation/archived/archived_screen.dart
  lib/presentation/archived/components/archived_item.dart
  lib/presentation/components/favorite_icon.dart
  lib/presentation/components/favorite_image.dart
  pubspec.yaml
Labels: feat

#191 Feat/ai recommend
  lib/core/enum/chat_case.dart
  lib/core/enum/chat_type.dart
  lib/core/router/router.dart
  lib/core/utils/markdown_util.dart
  lib/data/data_source/ai_data_source.dart
  lib/data/data_source/ai_data_source_impl.dart
  lib/data/repository_impl/ai_repository_impl.dart
  lib/di/di_setup.dart
  lib/domain/model/chat.dart
  lib/domain/repository/ai_repository.dart
  lib/domain/use_case/ai/get_chat_session_use_case.dart
  lib/domain/use_case/ai/send_chat_to_ai_use_case.dart
  lib/presentation/chat_bot/chat_bot_screen.dart
  lib/presentation/chat_bot/chat_bot_view_model.dart
  lib/presentation/chat_bot/components/chat_category_item.dart
  lib/presentation/chat_bot/components/chat_category_widget.dart
  lib/presentation/chat_bot/components/chat_input.dart
  lib/presentation/chat_bot/components/model_button_chat_widget.dart
  lib/presentation/chat_bot/components/model_chat_widget.dart
  lib/presentation/chat_bot/components/model_loading_widget.dart
  lib/presentation/chat_bot/components/user_chat_widget.dart
  lib/presentation/home/home_screen.dart
Labels: feat

#193 Styling/ format code
  lib/presentation/course_list/course_list_screen.dart
  lib/presentation/course_list/course_reccommendation_list.dart
  lib/presentation/location_list/location_list_screen.dart
Labels: feat

#194 refactor: di_setup 정리 및 UseCase getIt 추가
  lib/di/di_setup.dart
Labels: refactor

#199 fix: 로그인 경로 오류 수정
  lib/core/auth/user_provider.dart
  lib/data/repository_impl/auth/google_auth.dart
  lib/presentation/login/login_screen.dart
Labels: fix

#204 fix: 유저 정보를 부를 때마다 파이어베이스에 들어가는 것이 아닌 UserProvider를 이용
  lib/core/auth/user_provider.dart
  lib/presentation/components/common_app_bar.dart
  lib/presentation/my_page/my_page_edit_screen.dart
  lib/presentation/my_page/my_page_screen.dart
Labels: fix

#206 fix: HomeScreen의 앱바를 CommonAppBar로 수정
  lib/presentation/home/home_screen.dart
Labels: fix

#208 fix: 언어 변경을 누를 시 context의 Locale도 바뀌도록 수정
  lib/presentation/my_page/components/my_page_menu_list.dart
Labels: fix

#201 Feat/home top ten popular landmarks
  lib/data/data_source/firebase/liked_tour_data_source.dart
  lib/data/data_source/firebase/liked_tour_data_source_impl.dart
  lib/data/repository_impl/firebase/liked_tour_repository_impl.dart
  lib/di/di_setup.dart
  lib/domain/repository/firebase/liked_tour_repository.dart
  lib/domain/use_case/get_top_ten_popular_tour_list_use_case.dart
  lib/presentation/components/favorite_image.dart
  lib/presentation/home/home_screen.dart
  lib/presentation/home/home_view_model.dart
Labels: feat

#218 Refactor/change language and wording
  lib/domain/model/category/area_type.dart
Labels: refactor

#221 feat: home view model 수정
  lib/di/di_setup.dart
  lib/domain/use_case/get_area_data_use_case copy.dart
  lib/presentation/home/home_screen.dart
  lib/presentation/home/home_view_model.dart
Labels: refactor, fix

#223 Fix/apply cached network image
  lib/core/method/get_cached_network_image.dart
  lib/presentation/archived/components/archived_item.dart
  lib/presentation/components/cached_network_image_component.dart
  lib/presentation/components/favorite_image.dart
  lib/presentation/detail/detail_screen.dart
  lib/presentation/home/components/ongoing_festivals.dart
  lib/presentation/my_page/components/my_page_user_profile.dart
  lib/presentation/my_page/my_page_edit_screen.dart
  pubspec.yaml
Labels: feat, fix

#227 Fix/한국어일 경우에만 코스 정보가 보이도록 수정
  lib/presentation/course_list/course_list_screen.dart
  lib/presentation/course_list/course_reccommendation.dart
  lib/presentation/location_list/location_list_screen.dart
Labels: fix

#229 Feat/add chatbot language
  assets/translations/en-US.json
  assets/translations/ko-KR.json
  lib/data/data_source/ai_data_source_impl.dart
  lib/data/data_source/firestore_service.dart
  lib/data/data_source/liked_tour_data_source.dart
  lib/data/data_source/liked_tour_data_source_impl.dart
  lib/data/data_source/user_data_source.dart
  lib/data/data_source/user_data_source_impl.dart
  lib/data/repository_impl/liked_tour_repository_impl.dart
  lib/data/repository_impl/user_repository_impl.dart
  lib/di/di_setup.dart
  lib/domain/repository/liked_tour_repository.dart
  lib/domain/use_case/get_top_ten_popular_tour_list_use_case.dart
  lib/domain/use_case/like_tour_use_case.dart
  lib/domain/use_case/unlike_tour_use_case.dart
  lib/presentation/chat_bot/chat_bot_screen.dart
  lib/presentation/chat_bot/chat_bot_view_model.dart
  lib/presentation/chat_bot/components/model_button_chat_widget.dart
  lib/presentation/chat_bot/components/model_chat_widget.dart
  lib/presentation/home/home_screen.dart
  lib/presentation/home/home_view_model.dart
Labels: feat

#233 refactor: getDetailIcon에서 DetailIconUtil로 이동
  lib/core/method/get_detail_icon.dart
  lib/core/utils/detail_icon_util.dart
  lib/presentation/detail/detail_view_model.dart
Labels: refactor

#238 style: 검색 페이지 Input 디자인에 맞게 적용 및 기타 자잘한 수정
  lib/presentation/home/home_search_screen.dart
Labels: style

#240 Feat/create-near-by-tour-list
  lib/core/router/router.dart
  lib/di/di_setup.dart
  lib/domain/use_case/get_address_info_use_case.dart
  lib/presentation/components/common_text.dart
  lib/presentation/home/home_screen.dart
  lib/presentation/home/home_view_model.dart
  lib/presentation/nearby_list/nearby_list_screen.dart
  lib/presentation/nearby_list/nearby_list_view_model.dart
Labels: feat

#245 로그인 관련 수정 (로딩 추가, 제대로 로그인 안 되던 현상 수정)
  lib/presentation/login/login_screen.dart
  lib/presentation/login/login_view_model.dart
  lib/presentation/my_page/components/logout_dialog.dart
Labels: refactor

#248 마이페이지 메뉴바 수정
  assets/translations/en-US.json
  assets/translations/ko-KR.json
  lib/core/router/router.dart
  lib/presentation/my_page/components/my_page_menu_list.dart
Labels: feat

#247 feat: 무한 스크롤 추가
  lib/domain/use_case/get_search_keyword_usecase.dart
  lib/presentation/home/home_search_screen.dart
  lib/presentation/home/home_search_view_model.dart
Labels: feat

#251 Refactor/좋아요한 관광정보가 디테일 화면에서 바로 하트 반영이 안되던 부분 수정
  lib/core/auth/user_provider.dart
  lib/presentation/components/favorite_icon.dart
  lib/presentation/components/favorite_image.dart
Labels: refactor

#254 fix: 회원가입 버튼 클릭 후 user 정보 최신화
  lib/presentation/sign_up/sign_up_screen.dart
Labels: fix

#257 Refactor/create-near-by-screen
  lib/core/router/router.dart
  lib/di/di_setup.dart
  lib/domain/use_case/get_address_info_use_case.dart
  lib/presentation/components/common_text.dart
  lib/presentation/home/home_screen.dart
  lib/presentation/home/home_search_screen.dart
  lib/presentation/home/home_view_model.dart
  lib/presentation/nearby_list/nearby_list_screen.dart
  lib/presentation/nearby_list/nearby_list_view_model.dart
Labels: refactor
